---
    - name: start an instance with a public IP address
      # vars:
      #   type: "t2.medium"
      amazon.aws.ec2_instance:
        name: "ansible-instance"
        instance_type: "{{ type }}"
        security_group: default
        region: ap-south-1
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        network:
          assign_public_ip: true
        image_id: ami-0522ab6e1ddcc7055
        tags:
          Environment: Testing
